/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.so.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.liferay.so.model.SocialActivityGrouping;
import com.liferay.so.model.SocialActivityGroupingModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the SocialActivityGrouping service. Represents a row in the &quot;SO_SocialActivityGrouping&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.so.model.SocialActivityGroupingModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SocialActivityGroupingImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SocialActivityGroupingImpl
 * @see com.liferay.so.model.SocialActivityGrouping
 * @see com.liferay.so.model.SocialActivityGroupingModel
 * @generated
 */
public class SocialActivityGroupingModelImpl extends BaseModelImpl<SocialActivityGrouping>
	implements SocialActivityGroupingModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a social activity grouping model instance should use the {@link com.liferay.so.model.SocialActivityGrouping} interface instead.
	 */
	public static final String TABLE_NAME = "SO_SocialActivityGrouping";
	public static final Object[][] TABLE_COLUMNS = {
			{ "activityGroupingId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "classNameId", Types.BIGINT },
			{ "classPK", Types.BIGINT },
			{ "type_", Types.INTEGER },
			{ "activityIds", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table SO_SocialActivityGrouping (activityGroupingId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,classNameId LONG,classPK LONG,type_ INTEGER,activityIds VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table SO_SocialActivityGrouping";
	public static final String ORDER_BY_JPQL = " ORDER BY socialActivityGrouping.modifiedDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY SO_SocialActivityGrouping.modifiedDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.so.model.SocialActivityGrouping"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.so.model.SocialActivityGrouping"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.so.model.SocialActivityGrouping"),
			true);
	public static long CLASSNAMEID_COLUMN_BITMASK = 1L;
	public static long CLASSPK_COLUMN_BITMASK = 2L;
	public static long COMPANYID_COLUMN_BITMASK = 4L;
	public static long GROUPID_COLUMN_BITMASK = 8L;
	public static long TYPE_COLUMN_BITMASK = 16L;
	public static long USERID_COLUMN_BITMASK = 32L;
	public static long MODIFIEDDATE_COLUMN_BITMASK = 64L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.so.model.SocialActivityGrouping"));

	public SocialActivityGroupingModelImpl() {
	}

	public long getPrimaryKey() {
		return _activityGroupingId;
	}

	public void setPrimaryKey(long primaryKey) {
		setActivityGroupingId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return _activityGroupingId;
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return SocialActivityGrouping.class;
	}

	public String getModelClassName() {
		return SocialActivityGrouping.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("activityGroupingId", getActivityGroupingId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("classNameId", getClassNameId());
		attributes.put("classPK", getClassPK());
		attributes.put("type", getType());
		attributes.put("activityIds", getActivityIds());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long activityGroupingId = (Long)attributes.get("activityGroupingId");

		if (activityGroupingId != null) {
			setActivityGroupingId(activityGroupingId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long classNameId = (Long)attributes.get("classNameId");

		if (classNameId != null) {
			setClassNameId(classNameId);
		}

		Long classPK = (Long)attributes.get("classPK");

		if (classPK != null) {
			setClassPK(classPK);
		}

		Integer type = (Integer)attributes.get("type");

		if (type != null) {
			setType(type);
		}

		String activityIds = (String)attributes.get("activityIds");

		if (activityIds != null) {
			setActivityIds(activityIds);
		}
	}

	public long getActivityGroupingId() {
		return _activityGroupingId;
	}

	public void setActivityGroupingId(long activityGroupingId) {
		_activityGroupingId = activityGroupingId;
	}

	public long getGroupId() {
		return _groupId;
	}

	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	public Date getCreateDate() {
		return _createDate;
	}

	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		_columnBitmask = -1L;

		_modifiedDate = modifiedDate;
	}

	public String getClassName() {
		if (getClassNameId() <= 0) {
			return StringPool.BLANK;
		}

		return PortalUtil.getClassName(getClassNameId());
	}

	public void setClassName(String className) {
		long classNameId = 0;

		if (Validator.isNotNull(className)) {
			classNameId = PortalUtil.getClassNameId(className);
		}

		setClassNameId(classNameId);
	}

	public long getClassNameId() {
		return _classNameId;
	}

	public void setClassNameId(long classNameId) {
		_columnBitmask |= CLASSNAMEID_COLUMN_BITMASK;

		if (!_setOriginalClassNameId) {
			_setOriginalClassNameId = true;

			_originalClassNameId = _classNameId;
		}

		_classNameId = classNameId;
	}

	public long getOriginalClassNameId() {
		return _originalClassNameId;
	}

	public long getClassPK() {
		return _classPK;
	}

	public void setClassPK(long classPK) {
		_columnBitmask |= CLASSPK_COLUMN_BITMASK;

		if (!_setOriginalClassPK) {
			_setOriginalClassPK = true;

			_originalClassPK = _classPK;
		}

		_classPK = classPK;
	}

	public long getOriginalClassPK() {
		return _originalClassPK;
	}

	public int getType() {
		return _type;
	}

	public void setType(int type) {
		_columnBitmask |= TYPE_COLUMN_BITMASK;

		if (!_setOriginalType) {
			_setOriginalType = true;

			_originalType = _type;
		}

		_type = type;
	}

	public int getOriginalType() {
		return _originalType;
	}

	public String getActivityIds() {
		if (_activityIds == null) {
			return StringPool.BLANK;
		}
		else {
			return _activityIds;
		}
	}

	public void setActivityIds(String activityIds) {
		_activityIds = activityIds;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			SocialActivityGrouping.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SocialActivityGrouping toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (SocialActivityGrouping)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SocialActivityGroupingImpl socialActivityGroupingImpl = new SocialActivityGroupingImpl();

		socialActivityGroupingImpl.setActivityGroupingId(getActivityGroupingId());
		socialActivityGroupingImpl.setGroupId(getGroupId());
		socialActivityGroupingImpl.setCompanyId(getCompanyId());
		socialActivityGroupingImpl.setUserId(getUserId());
		socialActivityGroupingImpl.setCreateDate(getCreateDate());
		socialActivityGroupingImpl.setModifiedDate(getModifiedDate());
		socialActivityGroupingImpl.setClassNameId(getClassNameId());
		socialActivityGroupingImpl.setClassPK(getClassPK());
		socialActivityGroupingImpl.setType(getType());
		socialActivityGroupingImpl.setActivityIds(getActivityIds());

		socialActivityGroupingImpl.resetOriginalValues();

		return socialActivityGroupingImpl;
	}

	public int compareTo(SocialActivityGrouping socialActivityGrouping) {
		int value = 0;

		value = DateUtil.compareTo(getModifiedDate(),
				socialActivityGrouping.getModifiedDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		SocialActivityGrouping socialActivityGrouping = null;

		try {
			socialActivityGrouping = (SocialActivityGrouping)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = socialActivityGrouping.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		SocialActivityGroupingModelImpl socialActivityGroupingModelImpl = this;

		socialActivityGroupingModelImpl._originalGroupId = socialActivityGroupingModelImpl._groupId;

		socialActivityGroupingModelImpl._setOriginalGroupId = false;

		socialActivityGroupingModelImpl._originalCompanyId = socialActivityGroupingModelImpl._companyId;

		socialActivityGroupingModelImpl._setOriginalCompanyId = false;

		socialActivityGroupingModelImpl._originalUserId = socialActivityGroupingModelImpl._userId;

		socialActivityGroupingModelImpl._setOriginalUserId = false;

		socialActivityGroupingModelImpl._originalClassNameId = socialActivityGroupingModelImpl._classNameId;

		socialActivityGroupingModelImpl._setOriginalClassNameId = false;

		socialActivityGroupingModelImpl._originalClassPK = socialActivityGroupingModelImpl._classPK;

		socialActivityGroupingModelImpl._setOriginalClassPK = false;

		socialActivityGroupingModelImpl._originalType = socialActivityGroupingModelImpl._type;

		socialActivityGroupingModelImpl._setOriginalType = false;

		socialActivityGroupingModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<SocialActivityGrouping> toCacheModel() {
		SocialActivityGroupingCacheModel socialActivityGroupingCacheModel = new SocialActivityGroupingCacheModel();

		socialActivityGroupingCacheModel.activityGroupingId = getActivityGroupingId();

		socialActivityGroupingCacheModel.groupId = getGroupId();

		socialActivityGroupingCacheModel.companyId = getCompanyId();

		socialActivityGroupingCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			socialActivityGroupingCacheModel.createDate = createDate.getTime();
		}
		else {
			socialActivityGroupingCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			socialActivityGroupingCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			socialActivityGroupingCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		socialActivityGroupingCacheModel.classNameId = getClassNameId();

		socialActivityGroupingCacheModel.classPK = getClassPK();

		socialActivityGroupingCacheModel.type = getType();

		socialActivityGroupingCacheModel.activityIds = getActivityIds();

		String activityIds = socialActivityGroupingCacheModel.activityIds;

		if ((activityIds != null) && (activityIds.length() == 0)) {
			socialActivityGroupingCacheModel.activityIds = null;
		}

		return socialActivityGroupingCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{activityGroupingId=");
		sb.append(getActivityGroupingId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", classNameId=");
		sb.append(getClassNameId());
		sb.append(", classPK=");
		sb.append(getClassPK());
		sb.append(", type=");
		sb.append(getType());
		sb.append(", activityIds=");
		sb.append(getActivityIds());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("com.liferay.so.model.SocialActivityGrouping");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>activityGroupingId</column-name><column-value><![CDATA[");
		sb.append(getActivityGroupingId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>classNameId</column-name><column-value><![CDATA[");
		sb.append(getClassNameId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>classPK</column-name><column-value><![CDATA[");
		sb.append(getClassPK());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>type</column-name><column-value><![CDATA[");
		sb.append(getType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>activityIds</column-name><column-value><![CDATA[");
		sb.append(getActivityIds());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = SocialActivityGrouping.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			SocialActivityGrouping.class
		};
	private long _activityGroupingId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userUuid;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private Date _createDate;
	private Date _modifiedDate;
	private long _classNameId;
	private long _originalClassNameId;
	private boolean _setOriginalClassNameId;
	private long _classPK;
	private long _originalClassPK;
	private boolean _setOriginalClassPK;
	private int _type;
	private int _originalType;
	private boolean _setOriginalType;
	private String _activityIds;
	private long _columnBitmask;
	private SocialActivityGrouping _escapedModel;
}